### ISSUE TITLE
What is RPM error, 0000012B ?

### ISSUE THREAD

**Issue by ljuwon321** [jabbasj/CSGO-Cheat#2]
if i start ,it show me  What is RPM error, 0000012B

idk wht is this mean
1. const DWORD coords_offset = 0x00000134;
2. const DWORD plr_num_offset = 0x00000308; //???
3. const DWORD index_offset = 0x00000064;

is there
1. m_rgflCoordinateFrame 
2. dwClientState_MaxPlayer or dwPlayerResource 
3. m_iItemDefinitionIndex or dwWeaponTableIndex 

right?

**Comment by jabbasj** [comment]
The error means it didn't find information needed in memory (because the offsets have changed).

You can find the up to date offsets here: https://www.unknowncheats.me/forum/counterstrike-global-offensive/103220-global-offensive-structs-offsets-421.html

BTW the code is not up to date and it is detectable (you will get banned).

**Comment by BitesizedLion** [comment]
> 
> 
> The error means it didn't find information needed in memory (because the offsets have changed).
> 
> You can find the up to date offsets here: https://www.unknowncheats.me/forum/counterstrike-global-offensive/103220-global-offensive-structs-offsets-421.html
> 
> BTW the code is not up to date and it is detectable (you will get banned).

Hey, unsure if you still check Github but could you explain some of the offset names?

player_spotted_by_mask_offset
index_offset
coords_offset

**Comment by BitesizedLion** [comment]
Also for some reason I get 
`RPM error, 00000006`
instead of `RPM error, 0000012B`
After changing some of the offsets not sure what it means though.
